# Generated by Django 5.2.3 on 2025-06-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Toyota', 'Toyota'), ('BMW', 'BMW'), ('Volkswagen', 'Volkswagen'), ('Ford', 'Ford'), ('Audi', 'Audi'), ('Mercedes', 'Mercedes'), ('Hyundai', 'Hyundai'), ('Other', 'Other')], max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.PositiveIntegerField(help_text='Enter in kilometers')),
                ('city', models.CharField(choices=[('Belgrade', 'Belgrade'), ('Novi Sad', 'Novi Sad'), ('Niš', 'Niš'), ('Kragujevac', 'Kragujevac'), ('Subotica', 'Subotica'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
